name: Platform CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Platform.sh
      uses: actions/setup-java@v1
    - name: Deploy with Platform.sh
      env:
       HEADER: 'Content-Type: application/json'
       HOST: https://platform.sh/
      run: curl -H $HEADER -X GET $HOST
